/**
 * TanStack Query hooks for statistics data.
 * Fetches monthly breakdowns and multi-month totals from Supabase.
 */
import { useQuery } from "@tanstack/react-query";
import type moment from "moment";

import { supabase } from "@/lib/supabase";

interface MonthlyStatRow {
  payment_subtype_id: string;
  payment_subtype_name: string;
  payment_type_id: string;
  payment_type_name: string;
  total: number;
}

/** Fetches category breakdown for a single month. */
export function useMonthlyStats(month: moment.Moment) {
  const startOfMonth = month.clone().startOf("month").toISOString();
  const endOfMonth = month.clone().endOf("month").toISOString();

  return useQuery({
    queryKey: ["statistics", "monthly", startOfMonth],
    queryFn: async () => {
      const { data, error } = await supabase.rpc("get_monthly_stats", {
        start_date: startOfMonth,
        end_date: endOfMonth,
      });
      if (error) throw error;
      return data as MonthlyStatRow[];
    },
  });
}

interface MonthBucket {
  label: string;
  total: number;
}

/**
 * Fetches monthly totals for the last 6 months, optionally filtered by
 * payment type/subtype. Uses direct queries with timezone-safe boundaries
 * generated by moment (local time) to avoid UTC date_trunc mismatches.
 */
export function useMonthlyTotals(
  currentMonth: moment.Moment,
  paymentTypeId: string | null,
  paymentSubtypeId: string | null,
) {
  const monthKey = currentMonth.clone().startOf("month").toISOString();

  return useQuery({
    queryKey: [
      "statistics",
      "totals",
      monthKey,
      paymentTypeId,
      paymentSubtypeId,
    ],
    queryFn: async () => {
      /* Build 6 month boundaries using moment (local timezone). */
      const buckets: MonthBucket[] = [];

      for (let i = 5; i >= 0; i--) {
        const m = currentMonth.clone().subtract(i, "months");
        const start = m.clone().startOf("month").toISOString();
        const end = m.clone().endOf("month").toISOString();

        /* Query transaction_items joined with transactions and payment_subtypes. */
        let query = supabase
          .from("transaction_items")
          .select(
            "price, transactions!inner(transaction_date), payment_subtypes!inner(payment_type_id)",
          )
          .gte("transactions.transaction_date", start)
          .lte("transactions.transaction_date", end);

        if (paymentSubtypeId) {
          query = query.eq("payment_subtype_id", paymentSubtypeId);
        } else if (paymentTypeId) {
          query = query.eq("payment_subtypes.payment_type_id", paymentTypeId);
        }

        const { data, error } = await query;
        if (error) throw error;

        const total = (data ?? []).reduce(
          (sum, row) => sum + (row.price as number),
          0,
        );

        buckets.push({
          label: m.format("MMM"),
          total: Math.round(total * 10) / 10,
        });
      }

      return buckets;
    },
  });
}

/** Fetches payment subtypes filtered by payment type ID. */
export function usePaymentSubtypesByType(paymentTypeId: string | null) {
  return useQuery({
    queryKey: ["meta", "payment_subtypes", "by_type", paymentTypeId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("payment_subtypes")
        .select("id, name")
        .eq("payment_type_id", paymentTypeId as string)
        .order("name");
      if (error) throw error;
      return data as Array<{ id: string; name: string }>;
    },
    enabled: !!paymentTypeId,
  });
}
